/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/colors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks_page` | `/bookmarks_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/faq_page` | `/faq_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/helpers_page` | `/helpers_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map_page` | `/map_page`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/colors`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/bookmarks_page` | `/bookmarks_page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/faq_page` | `/faq_page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/helpers_page` | `/helpers_page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/map_page` | `/map_page`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/colors${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/bookmarks_page${`?${string}` | `#${string}` | ''}` | `/bookmarks_page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/faq_page${`?${string}` | `#${string}` | ''}` | `/faq_page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/helpers_page${`?${string}` | `#${string}` | ''}` | `/helpers_page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/map_page${`?${string}` | `#${string}` | ''}` | `/map_page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/colors`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/bookmarks_page` | `/bookmarks_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/faq_page` | `/faq_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/helpers_page` | `/helpers_page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/map_page` | `/map_page`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
